theme: jekyll-theme-merlot
title: Betsy Molgano
description: Welcome to my webisite for Machine Learning.


nav:
  - Home: index.md
  - Introduction: introduction.md
  - Conclusions: conclusion.md
  - DataPrep_EDA: dataprep_eda.md
  - Clustering: Clustering.md
  - PCA: pca.md
